### ISSUE TITLE
Move ESLint Rules to a Separate File

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#108]
# Overview

## Problem statement

Currently our eslint rules live in the `package.json` file. This makes it more difficult to read the `package.json` file as well as making it harder to add new rules or view the rules. 

## Proposed solutions

Move the rules from the `package.json` file to a separate `.eslintrc.json` file.

# Acceptance criteria

- ESLint rules no longer live in `package.json`
- ESLint rules live in a new `.eslintrc.json` file
- ESLint rules still work

**Comment by PuneetDabral** [comment]
sir can i also do this please assign this to me ..

**Comment by Chiradeep-Banik** [comment]
Hello I would like to work on this issue

**Comment by scottjr632** [comment]
Go for it!
