### ISSUE TITLE
Splash Screen Copywrite Text Position

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#109]
**Describe the bug**

On the splash screen of for ToyNet, the copywrite text is at the bottom of the screen without any padding. This text should be inline with the email contact and not below it.

**To Reproduce**
1. Go to [toynet.projectreclass.org](https://toynet.projectreclass.org]
2. Scroll down to the bottom of the page
4. See position of copywrite text

**Expected behavior**

The copywrite text should be inline with the email contact text and not below it.

**Screenshots**

![image](https://user-images.githubusercontent.com/22752497/132543412-e64c5b9f-3063-4487-b05b-8b2e3017861d.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome, Edge, Firefox

**Comment by PuneetDabral** [comment]
sir can i do this so i can learn more from you.....

**Comment by demonicirfan** [comment]
Hii, Iam a beginer and new to open source, I want to get started with open source so can i work on this.

**Comment by scottjr632** [comment]
Go for it!
Make sure to check out the [Contribution Guidelines](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) before getting started.

**Comment by demonicirfan** [comment]
I have gone through the Contribution Guidelines and I have added the bottom padding of 4vw and it's now in line with the email Contact, is it all I have to do. I am new and I don't have any idea please guide me @scottjr632

**Comment by scottjr632** [comment]
Please make a pull request from your fork to the master branch of this repository with the changes that you have made so that those changes can be reviewed and merged in.

**Comment by demonicirfan** [comment]
I have done the pull request please look into it and thanks for giving me this opportunity.
