### ISSUE TITLE
Remove Sign In and Sign Up Button on Splash Page

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#110]
# Overview

## Problem statement

Currently login and sign are not enabled for toynet. These should be removed so that this does not confuse users.

## Proposed solutions

Hide the buttons behind a feature flag or just remove them.

# Acceptance criteria

- The sign in and sign-up buttons are no longer visible.

# Designs

![image](https://user-images.githubusercontent.com/22752497/132545288-83d91920-8b9e-4128-ac4f-3c859973eaab.png)

![image](https://user-images.githubusercontent.com/22752497/132545357-997ddc93-3b29-437e-b43b-9ee707ef3a8f.png)

**Comment by PuneetDabral** [comment]
please assign it to me ..(i am new in open source also i need your support so i can motivate myself to word open source)..thanku

**Comment by scottjr632** [comment]
Hi there! I noticed you commented on a couple other issues. I will assign you to this issue for the moment. After you complete this issue feel free to comment on another issue that has a "Help Wanted" tag and I will assign to you if its open.

Please make sure to check out the [Contribution Guidelines](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) before contributing.

**Comment by PuneetDabral** [comment]
ok sir

**Comment by PuneetDabral** [comment]
sir can you give me more beginner friendly issue? so i can learn more

**Comment by scottjr632** [comment]
You are welcome to comment on any tickets that have a "help wanted" tag on them. Tickets with a "good first issue" are generally easier tickets. We will be adding more issues periodically.

**Comment by PuneetDabral** [comment]
ok sir feel free to tell me .. i need to learn from you..
