### ISSUE TITLE
Better Page Not Found Page

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#111]
# Overview

## Problem statement

Currently the "page not found" page is a bit sparse. This page should at least have the text to be larger and more noticeable. This page should also include a link back to the [ToyNet splash screen](https://toynet.projectreclass.org)

## Proposed solutions

Make the "Page not found" text to be much larger and centered in the page. 
Add a link that goes back to the splash screen.

# Acceptance criteria

- Text is much larger and easier to read
- Text is centered both vertically and horizontally
- Includes link back to the splash screen

# Designs

**Current**:
![image](https://user-images.githubusercontent.com/22752497/132545830-d370a04d-e939-4704-bb84-a8bc309884e4.png)

**Updated**:
![image](https://user-images.githubusercontent.com/22752497/132546202-d147db12-d6eb-4c28-951b-096c4a0cb5f4.png)

**Comment by Chiradeep-Banik** [comment]
Hello, I would like to work on this. Can to point me to where the current page is?

**Comment by scottjr632** [comment]
Hey there! 
You need to create a new component in the `src/common/components/` directory called `NotFound.tsx` that looks like the updated screenshot in the issue description. You will then add that component to [this](https://github.com/Project-Reclass/toynet-react/blob/master/src/App.tsx#L106) line and replace the`h1` tag that is there. The 'Return home' text should link back to the `/` path. 

Also be sure to check the [Contribution Guide](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) before getting started!
