### ISSUE TITLE
Clicking on the curriculum icon does not link to the dashboard

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#122]
**Describe the bug**

When clicking on the curriculum icon on the sidebar, the user is not taken to the `/curriculum` page.

**To Reproduce**
1. Go to the `/module/1/emulator/1`.
2. Mover mouse over the sidebar.
3. Click on the curriculum icon.
4. Notice that nothing happens.

**Expected behavior**

When a user clicks on the curriculum icon, then the user should be taken to `/curriculum`.
Adding the below around the curriculum icon should fix the issue.

```jsx
<StyledNavItem onClick={() => goToPageOnEnableHref('/curriculum')}>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/22752497/133143715-80f2b30a-6995-4dba-acd2-2ff5bb091c1c.png)

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by Chiradeep-Banik** [comment]
Hey can you tell me how to reproduce the bug ??

**Comment by scottjr632** [comment]
@Chiradeep-Banik Please see the updated steps in the "To Reproduce" section of the issue description.

**Comment by scottjr632** [comment]
@Chiradeep-Banik Did you want to take a swing at solving this bug?
