### ISSUE TITLE
Migrate `Survey.test.jsx` to Typescript

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#125]
# Overview

## Problem statement

We currently have our tests written in JS. We want to migrate to have everything in Typescript to have uniformity in our codebase. 

## Proposed solutions

Migrate `src/__tests__/ModuleList/Survey/Survey.test.jsx` to Typescript.

See `/src/__tests__/ModuleList/Value/Value.test.tsx` for an example.

# Acceptance criteria

- The Survey Test unit test file is migrated to Typescript

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by Wodorek** [comment]
Hey, I already wrote the code for this issue, can you please assign it, and I'll make a PR

**Comment by Wodorek** [comment]
Please assign me this issue.

**Comment by scottjr632** [comment]
Go for it!
