### ISSUE TITLE
Migrate `ModuleList.test.jsx` to Typescript

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#128]
# Overview

## Problem statement

We currently have our tests written in JS. We want to migrate to have everything in Typescript to have uniformity in our codebase. 

## Proposed solutions

Migrate `src/__tests__/ModuleList/ModuleList.test.jsx` to Typescript.

See `src/__tests__/ModuleList/Value/Value.test.tsx` for an example.

# Acceptance criteria

- The Module List Test unit test file is migrated to Typescript

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by Wodorek** [comment]
Hey, I already wrote the code for this issue, can you please assign it, and I'll make a PR

**Comment by scottjr632** [comment]
@Wodorek Sure thing! I will assign this one to you. Once the PR for this is merged then I can assign you to another one. We try to assign people to only one issue at a time. I will delete your comments on the other issues for right now in case someone else wants to work on them.

As well, please check out our [Contribution guide](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) to make sure you're contributing correctly.
