### ISSUE TITLE
Migrate `SubModule.test.jsx` to Typescript

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#129]
# Overview

## Problem statement

We currently have our tests written in JS. We want to migrate to have everything in Typescript to have uniformity in our codebase. 

## Proposed solutions

Migrate `src/__tests__/ModuleList/Module/SubModule/SubModule.test.jsx` to Typescript.

See `src/__tests__/ModuleList/Value/Value.test.tsx` for an example.

# Acceptance criteria

- The SubModule Test unit test file is migrated to Typescript

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by nishit-prasad** [comment]
Hello, I am fairly new to Typescript and would like to work on this to expand my skillset. Can I take this up if it's available?

**Comment by scottjr632** [comment]
Go for it!

Also be sure to see our [Contribution guide}(https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) before you get started!

**Comment by Wodorek** [comment]
I see that nishit is already assigned that issue, but I can do it too, if need be.

**Comment by scottjr632** [comment]
@nishit-prasad any progress on this issue?

**Comment by scottjr632** [comment]
@nishit-prasad I am un-assigning you from this issue for right now. You're welcome to pick up a new issue.

**Comment by Wodorek** [comment]
I created a PR for this issue, since it is "free".
