### ISSUE TITLE
Migrate `useAuthState.test.jsx` to Typescript

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#134]
# Overview

## Problem statement

We currently have our tests written in JS. We want to migrate to have everything in Typescript to have uniformity in our codebase. 

## Proposed solutions

Migrate `src/__tests__/Login/AuthProvider/useAuthState.test.jsx` to Typescript.

See `src/__tests__/ModuleList/Value/Value.test.tsx` for an example.

# Acceptance criteria

- The useAuthState Test unit test file is migrated to Typescript

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by bmw2621** [comment]
Requires update to Action type at `src/common/types.ts` line 42.  Because payload is required, `src/__tests__/Login/AuthProvider/useAuthState.test.tsx` line 42  will not run (currently no payload).

Will there be a problem if  payload attribute of Action type is made optional?

**Comment by bmw2621** [comment]
Ill take this one BTW!

**Comment by scottjr632** [comment]
> Requires update to Action type at `src/common/types.ts` line 42. Because payload is required, `src/__tests__/Login/AuthProvider/useAuthState.test.tsx` line 42 will not run (currently no payload).
> 
> Will there be a problem if payload attribute of Action type is made optional?

_commenting here for future documentation_

Let's just pass in an empty object for right now. I will create a ticket later to update `payload` on the `Action` type to be optional since I believe there are other files that use it.

```
result.current[1]({ type: AuthActions.LOGOUT, payload: {} })
```
