### ISSUE TITLE
Make `Action.payload` optional 

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#147]
# Overview

## Problem statement

Currently the `Action` type used in our reducers does not allow the payload to be optional when there are some instances where the payload should be optional (e.g. when logging out).

## Proposed solutions

Make the `Action` type defined in `src/common/types.ts` optional and making sure each area of code that uses this type now accounts for this new optional payload.

# Acceptance criteria

- The payload is optional
- Tests continue to work
- Every part of the code that uses this type accounts for this now being optional.

**Comment by scottjr632** [comment]
@bmw2621

**Comment by bmw2621** [comment]
On it
