### ISSUE TITLE
Sidebar curriculum does not match the rest if icons

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#166]
**Describe the bug**

The curriculum icon on the sidenav does not match the other icons (e.g. Profile, FAQ, Logout). 

**To Reproduce**
1. Go http://localhost:3000/module/1/emulator/1
2. Hover over the sidebar.
3. Hover over the Profile, FAQ, and Logout notice the teal line to the border left.
4. Hover over the curriculum and notice how there is not the border left. 

**Expected behavior**

There should be a teal border to the left that matches the rest of the icons.

**Screenshots**

https://user-images.githubusercontent.com/22752497/134038303-7bb820b6-f474-4b4d-8180-9daecef2e880.mov

**Additional context**

See the styled component `StyledNavItem` in the `Sidebar.tsx` and lines 135-142 for an example.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by springsnow** [comment]
Hi, I'll take this one for my first try.

**Comment by scottjr632** [comment]
You got it!
