### ISSUE TITLE
Splash screen icon too large on wide screens

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#168]
**Describe the bug**

Currently the icon is very large on a widescreen monitor.

**To Reproduce**

**Expected behavior**

This icon should be more consistent across various monitor widths. Currently the `max-width: 25%` if we change it to `25rem` instead it would be more consistent.  

**Screenshots**

**Currently looks like:**
![image](https://user-images.githubusercontent.com/22752497/134041650-59c1beb2-1455-45b9-82c0-d2d727e73245.png)

**Should look like:**
![image](https://user-images.githubusercontent.com/22752497/134041772-583d23d0-2255-43f9-a966-2645891ce715.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chromium Edge
 - Screen dimensions: 2560x1920

**Additional context**
Using `max-width: 25rem` should fix this issue.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by misakimichy** [comment]
I'm going to assign this issue!

**Comment by scottjr632** [comment]
You got it!

**Comment by scottjr632** [comment]
@misakimichy Any progress on this issue or need any help?

**Comment by misakimichy** [comment]
@scottjr632 
Sorry for not giving you an update. I've been busy with my work + preparing for my family-in-laws memorial service. Today's pretty busy with work too, so I can do it tomorrow or you can unassign me from this issue!

**Comment by scottjr632** [comment]
> @scottjr632 Sorry for not giving you an update. I've been busy with my work + preparing for my family-in-laws memorial service. Today's pretty busy with work too, so I can do it tomorrow or you can unassign me from this issue!

No worries! I'll keep you on for another week since this issue is low priority. But Let me know if you don't think you'll be able to finish it 😃
