### ISSUE TITLE
 Add ability to have color in actions history

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#172]
# Overview

## Problem statement

Currently, the actions history doesn't have the ability to have any color to it. This makes it difficult to differentiate between successful operations and errors. There should be a way to specify a color to the [appendDialogue](https://github.com/Project-Reclass/toynet-react/blob/main/src/Emulator/EmulatorProvider.tsx#L42) function and have that be able to render the text with a color.

## Proposed solutions

Update `appendDialogue` to accept an optional parameter color (e.g. `appendDialogue(message: string, color: string)`. Then a new data structure to hold the message and color could be stored in the `dialogueMessages` array so that the color can be rendered later. 

# Acceptance criteria

- A color options is available to the `appendDialogue` function.
- Colored text is rendered in the actions history panel of the emulator.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by Wodorek** [comment]
I created a PR for this issue, is that what you had in mind?
