### ISSUE TITLE
Add color to error action messages

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#179]
# Overview

## Problem statement
Currently when there is an error message added to the action history panel there is no way to differentiate it from the other messages.

## Proposed solutions
Make the error text added by the link validators red.
FYI - Chakra color red is `tomato`

# Acceptance criteria
- Errors caused from link validators are red

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by Wodorek** [comment]
I made a PR for this issue
