### ISSUE TITLE
Better padding in actions pane

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#184]
**Describe the bug**
The text in the actions pane is a little too close to the edge of the box. There should be more padding.

**Expected behavior**
A small padding is added to the actions pane so that the icons are not touching the sides of the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/22752497/134548299-eadc6221-8378-4d54-9998-0fba9948b081.png)

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by springsnow** [comment]
I'll do it :-)
Would you like me to match the paddings for all 3 boxes:  **Actions**, **Console**, and **Tasks**?
I see that **Tasks** currently has inline-styled padding of 0.549rem.

**Comment by scottjr632** [comment]
That sounds great! Thanks!
