### ISSUE TITLE
Disable using delete key in the Visual Panel

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#189]
# Overview

## Problem statement

Currently a user can delete a node using the `Delete` or `Backspace` key. This causes issues with our topologies as we do not allow deleting a node if there are connections.

## Proposed solutions

Disable using the delete key in the Visual Panel. Setting the prop of `deleteKeyCode: number | string default: Backspace` to something like undefined in the `ReactFlow` component in `src/Emulator/Visuals/Flow/Flow.tsx` should fix this issue.

# Acceptance criteria

- When a use clicks on a node and presses the backspace button, the node **_is not_** deleted.
- A use can still right click a node to delete it.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by misakimichy** [comment]
I'm going to work on this issue!

**Comment by scottjr632** [comment]
Great, thanks!
