### ISSUE TITLE
Remove the "back to site" link in instructions panel

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#263]
# Overview

## Problem statement
Currently, there is a link on the emulator that takes you back to the splash screen. This link is currently not relevant anymore since the implementation of the curriculum.

## Proposed solutions
Delete the "back to site" link in the instructions panel

![image](https://user-images.githubusercontent.com/22752497/139966397-4628de74-75fc-4362-9d42-960865edd9ad.png)

# Acceptance criteria
- The "back to site" link is removed
- Snapshots are updated and all tests pass

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by misakimichy** [comment]
I'll take it.
