### ISSUE TITLE
Open next module on redirect back to dashboard when completing module

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#265]
# Overview

## Problem statement
When you finish a module and it takes you back to the dashboard (e.g. [/dashboard/1](https://toynet.projectreclass.org/dashboard/1)) the next module that the user should work on is not shown. This can be confusing to the user as to which module they should work on next.

## Proposed solutions
Update the `src/common/api/curriculum/dashboard/hooks.ts/useCurriculumNavigator` to update the link that goes to the dashboard when the module is done to include `?module={next module index}`. This will allow the next module to be shown.

# Acceptance criteria
- When complete a module, and clicking the "Complete Module" button, then the page redirect back to the home screen, and the next module is expanded, and all of the previous modules are minimized.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by De1ain** [comment]
Hi @scottjr632, please assign this issue to me.

**Comment by scottjr632** [comment]
You got it!
