### ISSUE TITLE
Update the curriculum dashboard to be easier to navigate

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#278]
# Overview

## Problem statement
There is currently a problem with how the [curriculum dashboard](https://www.toynet.projectreclass.org/dashboard/1?module=0) navigates. It is not clear to the user how to get to the actual submodule.

## Proposed solutions
Remove the collapsable description below the submodule title and just include the description without it being collapsable. 
Replace the "Go to submodule >" text with a play button.

# Acceptance criteria
- Submodule description is not collapsable and is visible by default
- The "Go to submodule" link is replaced with a Play button.

# Designs
Inspiration (ignore colors)
![image (3)](https://user-images.githubusercontent.com/22752497/142672435-9abb9258-6b61-4f58-b6d4-21d2a119361f.png)

# Related documents
- You can use [react-icons](https://react-icons.github.io/react-icons/) to find a good play button.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by scottjr632** [comment]
@misakimichy I created the issue here. Let me know if you have any questions 😄

**Comment by misakimichy** [comment]
@scottjr632 @takakonishimura
I guess eaither of these icons would work. think 2 with a white border + white triangle will look great. What do you think?
1. <img width="125" alt="Screen Shot 2021-11-19 at 21 37 56" src="https://user-images.githubusercontent.com/42012999/142713271-0edf8817-9a6f-4cdf-b44c-731f335b3551.png"> 2. <img width="119" alt="Screen Shot 2021-11-19 at 21 42 22" src="https://user-images.githubusercontent.com/42012999/142713334-b076d47b-e33b-4760-8b30-d404db8f899d.png"> 3. <img width="109" alt="Screen Shot 2021-11-19 at 21 39 43" src="https://user-images.githubusercontent.com/42012999/142713283-15081b31-9c5f-48a0-88e2-f27b96f88ed3.png">

Question:
Should I rotate the play button like a screenshot? I guess that is just an example and I can go with the normal play button that points to the right?

**Comment by scottjr632** [comment]
I like the second one as well 😄 

I think the play button should not be rotated, because then if it is rotated, it doesn't really look like a play button.

**Comment by misakimichy** [comment]
Makes sense about the rotation of the play button 😹

**Comment by takakonishimura** [comment]
![image](https://user-images.githubusercontent.com/4872808/142745877-e016dd0e-9ae1-497a-85cc-5ee627f7ae6b.png)
Can we update the text at the top with this change to reflect our current navigation?
