### ISSUE TITLE
Update max-width of Lectures and Articles to 700px

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#283]
# Overview

## Problem statement
Currently, the max-width of the articles and lecture sub-modules makes it difficult to read. 

## Proposed solutions
Set the `max-width` of the article and lecture pages to be 700px.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by 4-Leafs-Code** [comment]
I was working on this issue. I think I might have fixed it. I emailed you some questions I had.
