### ISSUE TITLE
Increase connection circles to be 10px

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#286]
# Overview

## Problem statement
The current circles on the nodes are too small. This makes it difficult to make connections. 

## Proposed solutions
Increase the size of the circles to be 10px for height and width.

# Acceptance criteria
- The nodes connections of both the left and the right have a height and width of 10px.

**Reference Image**
![image](https://user-images.githubusercontent.com/22752497/143287323-e9f1c428-025d-4e8e-a459-89ef432f45e3.png)

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by byw2** [comment]
Can I please be assigned to this? thanks!
