### ISSUE TITLE
Change the font of IP addresses to be monotype

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#287]
# Overview

## Problem statement
The current font being used for the IP addresses makes it difficult to read at times.

## Proposed solutions
Change the font type to be a monotype font.

# Acceptance criteria
- The font of all IP address inputs is a monotype font.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by 4-Leafs-Code** [comment]
Are you referring to the <FormControl>..../FormControl> on line 150 of CreateHostView.tsx and line 145 of CreateRouterView.tsx? Are these the forms that need to be affected by the input fonts?
