### ISSUE TITLE
Change the default text of the navigation to be "Next" and "Previous"

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#288]
# Overview

## Problem statement
The current default text of the curriculum navigation is "Next Submodule" and "Previous Submodule" this is often too long for the page.

## Proposed solutions
Change the default text to be "Next", "Previous"  and "Complete" and make sure that this is propagated to all of the pages so that no page has "Next submodule" etc...

# Acceptance criteria
- No pages have "Next submodule", "Previous submodule", or "Complete submodule"
- All pages have "Next", "Previous" or "Complete" instead.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by misakimichy** [comment]
I'll take it!
