### ISSUE TITLE
Get rid of grey box in the video page

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#289]
# Overview

## Problem statement
The grey box in the video page makes it feel like a modal.

## Proposed solutions
Get rid of the grey box and move the text and description above the image.

# Acceptance criteria
- The grey box in the video page is no longer there.
- The title and description are above the video.

# Designs

![image (4)](https://user-images.githubusercontent.com/22752497/143288457-875a0ffd-83cc-49be-b915-13134b477b68.png)

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by misakimichy** [comment]
I'll take it.
