### ISSUE TITLE
Ensure Y margin for all submodules is the same

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#290]
# Overview

## Problem statement
Currently, there are pages where the margin Y is different from one submodule to another submodule. Specifically on the article and lecture page.

## Proposed solutions
Ensure that all the Y margins surrounding the article and lecture page are the same.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

**Comment by De1ain** [comment]
Hi @scottjr632, please assign this issue to me.

**Comment by scottjr632** [comment]
You got it!
