### ISSUE TITLE
Survey Page

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-react#95]
# Overview

## Problem statement

We want to be able to capture user's thoughts on the content and how they're learning. 

## Proposed solutions

Create a new survey page which provides the user with a variety of answer types such as text, choice, scale. Use [this](https://github.com/Project-Reclass/toynet-content/blob/main/data/survey/6001/meta.json) as a reference to what the data will look like. This does not need any communication with the backend right now as that is still a WIP.

# Acceptance criteria

- Page renders the questions in [this file](https://github.com/Project-Reclass/toynet-content/blob/main/data/survey/6001/meta.json).
- There should be multiple types rendered as defined in the linked file.
- A new route is added for this new page that accepts a module id and survey id [see this line for an example](https://github.com/Project-Reclass/toynet-react/blob/master/src/App.tsx#L43).
- There should be a way for the user to submit the quiz (it does not to do anything right now).

# Designs

![image](https://user-images.githubusercontent.com/22752497/131368571-31df4a0b-8459-4c17-b15e-54f590abd6da.png)

# Related documents

- [Example data](https://github.com/Project-Reclass/toynet-content/blob/main/data/survey/6001/meta.json)
- Additional wire frame ![image](https://user-images.githubusercontent.com/22752497/131370744-3ed3cc8e-fdb0-4edc-8461-3af2fefae3ca.png)

**Comment by orholam** [comment]
PR: https://github.com/Project-Reclass/toynet-react/pull/103
